### ISSUE TITLE
New logo for Qlist

### ISSUE THREAD

**Issue by reallinfo** [SloCompTech/QList#9]
I wanted to contribute to Qlist I designed a logo for Qlist. If you like it, I'll send you the files.

![qlist](https://user-images.githubusercontent.com/36298335/37924391-6d708d3a-313a-11e8-9ee4-15274aa6f03b.jpg)

**Comment by SloCompTech** [comment]
Hi,
thanks for your hard work. You created really fantastic logo. 

Do you know how to use git ? If you do, would you mind forking this repo, adding logo image in root of this repo as `logo.extension` and adding it to `README.md` as image (markdown syntax), then create pull request ?

In case you don't know, you can send me files to slocomptech@gmail.com, but in this case your contribution won't be shown in github contributors (I think, but not sure), but I would add your name in list of contributors, if that's OK ?

Cheers

**Comment by reallinfo** [comment]
Hello, I do not use Github very well. I don't want to ruin the repository :) I will send you mail. Thank you for accepting the logo.

**Comment by SloCompTech** [comment]
Thanks, do you want that I include you real name in contributors list or only your username ?

**Comment by reallinfo** [comment]
You can add my username to the list. Which logo do you prefer? Left or right?

**Comment by SloCompTech** [comment]
I prefer left logo.

**Comment by reallinfo** [comment]
I will prepare and send the all files as soon as possible. Good works!
